<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.15"/>
        <PackageReference Include="NLog" Version="5.0.5" />
        <PackageReference Include="NLog.Database" Version="5.0.5" />
        <PackageReference Include="NLog.Extensions.Hosting" Version="5.0.4" />
        <PackageReference Include="NLog.Web.AspNetCore" Version="5.1.5" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GnuHiveApi.Common\GnuHiveApi.Common.csproj" />
      <ProjectReference Include="..\GnuHiveApi.Persistence.Command\GnuHiveApi.Persistence.Command.csproj" />
      <ProjectReference Include="..\GnuHiveApi.Persistence\GnuHiveApi.Persistence.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Authentication\" />
      <Folder Include="SharedConfig\" />
    </ItemGroup>

</Project>
